from typing import Dict, Literal

ThemeType = Literal["light", "dark", "contrast", "ocean"]

THEMES: Dict[ThemeType, dict] = {
    "light": {
        "bg": "#f5f5f5",
        "fg": "#2c3e50",
        "surface": "#ffffff",
        "surface_hover": "#f0f0f0",
        "primary": "#3498db",
        "primary_hover": "#2980b9",
        "secondary": "#95a5a6",
        "accent": "#e74c3c",
        "success": "#27ae60",
        "border": "#dcdcdc",
        "text_primary": "#2c3e50",
        "text_secondary": "#7f8c8d",
        "text_on_primary": "#ffffff",
        "shadow": "#00000015",
        "table_header": "#ecf0f1",
        "table_row_even": "#ffffff",
        "table_row_odd": "#fafafa",
        "table_hover": "#e8f4f8",
    },
    "dark": {
        "bg": "#1a1a1a",
        "fg": "#e0e0e0",
        "surface": "#2d2d2d",
        "surface_hover": "#3a3a3a",
        "primary": "#3498db",
        "primary_hover": "#5dade2",
        "secondary": "#5a6c7d",
        "accent": "#e74c3c",
        "success": "#2ecc71",
        "border": "#404040",
        "text_primary": "#e0e0e0",
        "text_secondary": "#a0a0a0",
        "text_on_primary": "#ffffff",
        "shadow": "#00000040",
        "table_header": "#3a3a3a",
        "table_row_even": "#2d2d2d",
        "table_row_odd": "#252525",
        "table_hover": "#1e3a52",
    },
    "contrast": {
        "bg": "#000000",
        "fg": "#ffffff",
        "surface": "#1a1a1a",
        "surface_hover": "#2a2a2a",
        "primary": "#ffff00",
        "primary_hover": "#ffff66",
        "secondary": "#808080",
        "accent": "#ff00ff",
        "success": "#00ff00",
        "border": "#ffffff",
        "text_primary": "#ffffff",
        "text_secondary": "#cccccc",
        "text_on_primary": "#000000",
        "shadow": "#ffffff20",
        "table_header": "#2a2a2a",
        "table_row_even": "#1a1a1a",
        "table_row_odd": "#0f0f0f",
        "table_hover": "#333300",
    },
    "ocean": {
        "bg": "#e0f2f7",
        "fg": "#004d61",
        "surface": "#ffffff",
        "surface_hover": "#f0f9fb",
        "primary": "#0097a7",
        "primary_hover": "#00acc1",
        "secondary": "#607d8b",
        "accent": "#ff6f00",
        "success": "#00897b",
        "border": "#b2dfdb",
        "text_primary": "#004d61",
        "text_secondary": "#546e7a",
        "text_on_primary": "#ffffff",
        "shadow": "#00000010",
        "table_header": "#b2ebf2",
        "table_row_even": "#ffffff",
        "table_row_odd": "#f1f9fa",
        "table_hover": "#e0f7fa",
    },
}